### ISSUE TITLE
Error with Node 8.7 & Electron 1.8.1

### ISSUE THREAD

**Issue by arcovoltaico** [dhleong/node-apple-remote#5]
After installing node-apple -remote when I include this code on my angulaJS controller:
`// APPLE REMOTE
var AppleRemote = require('node-apple-remote');
`

i get this console error (although I tried to rebuild etc)

app threw an error during load
Error: The module '/Users/a77/Documents/DEV/Uvox 5 Player/node_modules/node-hid/build/Release/HID.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/a77/Documents/DEV/Uvox 5 Player/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/Users/a77/Documents/DEV/Uvox 5 Player/node_modules/node-hid/nodehid.js:5:34)

**Comment by dhleong** [comment]
It looks like you're using Electron. See:

https://github.com/node-hid/node-hid#using-node-hid-in-electron-projects

**Comment by arcovoltaico** [comment]
Already add the script ... but no luck

**Comment by dhleong** [comment]
Other than suggesting you delete the node-hid directory, verifying you're specifying the right version of electron, and re-installing... not sure what else to suggest. This looks like a node-hid install/config issue to me.

**Comment by arcovoltaico** [comment]
Already tried that … maybe with bad numbers on the package.json … which ones are working ?
Thanks

**Comment by dhleong** [comment]
It has to match the version of electron you're using. 

It's complaining that the version of node.js it was compiled for is not the version of node.js it's using; electron packages its own node.js runtime, and that version is not the same one you're compiling it with.

**Comment by arcovoltaico** [comment]
I’ll try further and let you know asap. Thx!!!
